on:
  pull_request:
  push:
    branches:
      - main

name: Lint

jobs:
  client_linter:
    name: Chariot Client Linter
    runs-on: ubuntu-latest
    steps:
      # required for gilrs, rodio
      - name: Install build dependencies
        run: sudo apt-get install -y libudev-dev pkg-config libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path chariot-client/Cargo.toml -- --no-deps
  core_linter:
    name: Chariot Core Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path chariot-core/Cargo.toml -- --no-deps
  server_linter:
    name: Chariot Server Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path chariot-server/Cargo.toml -- --no-deps
