on:
  pull_request:
  push:
    branches:
      - main

name: Build

jobs:
  client_build_test:
    name: Chariot Client Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path chariot-client/Cargo.toml --check
  core_build_test:
    name: Chariot Core Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path chariot-core/Cargo.toml --check
  server_build_test:
    name: Chariot Server Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path chariot-server/Cargo.toml --check
          